
# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f17314070174709f092cbed38adad43c497676c4c15952914a44b9cc2d23701c998649e54164603b5296addb852b1fb499364d581c97cae950ba18257405772
  facebook_app_id: 1052333978199022
  facebook_app_secret: 7165bd1a8c6ef0c745d3037122aa8ecf
  twitter_app_key:     XkVbpCrqJtss3bVrYYTASg2na
  twitter_app_secret: 50i3d6g454bTgBnNnMlFidjxY6VhTanO0wkC05m3Dg8d0JGuin
test:
  secret_key_base: 696ce632006fdbe9ce4529e9258a942f8c4b60a4bfb32a95385242db1060ccca41c1b6094fcf38fb4e9b0bd43ad8f197e8e9bcc6038ba50600a1c930670d74c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_app_key: <%= ENV["TWITTER_APP_ID"] %>
  twitter_app_secret: <%= ENV["TWITTER_APP_SECRET"] %>